### ISSUE TITLE
Does not build on Mac Catalyst anymore

### ISSUE THREAD

**Issue by robertying** [react-native-push-notification-ios/push-notification-ios#101]
# Bug

Starting with v1.1.0, this does not build for Mac Catalyst target anymore, even after I manually delete all the conditional macro checks.

v1.0.7 works fine.

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/push-notification-ios

Haven't tested it fully but it compiles on iOS and Catalyst.

**Comment by cuttlas** [comment]
Any news on this? We are facing the same problem. We don't need the notifications to work in Mac Catalyst but at least we do need the build to succeed. 

Thanks.

**Comment by Naturalclar** [comment]
@robertying @cuttlas 
Sorry for taking so long, I've released v1.7.1 that allows building for Mac Catalyst
Works with new features added in v1.7.0 :tada:

<img width="1116" alt="Screen Shot 2020-10-26 at 6 47 30 PM" src="https://user-images.githubusercontent.com/6936373/97160386-9f13cf00-17bf-11eb-9569-e218218a0613.png">

**Comment by cuttlas** [comment]
Awesome! Thanks
