### ISSUE TITLE
presentLocalNotification doesn't work

### ISSUE THREAD

**Issue by artemkhalygov** [react-native-push-notification-ios/push-notification-ios#105]
Could you please help me. This code not working:

`PushNotificationIOS.presentLocalNotification({
 alertTitle: 'test',
 alertBody: 'test2',
})` 
I configured AppDelegate.m and AppDelegate.h according your instructions, but can't show any notifications in foreground. React Native v0.62.2.

**Comment by bhargav501** [comment]
I am experiencing the same issue. same react-native version :(

**Comment by Mura7** [comment]
+1  [https://github.com/zo0r/react-native-push-notification/issues/1371#issuecomment-616403462](url)

```
    "react-native": "0.62.1",
    "@react-native-community/push-notification-ios": "^1.1.1",
```

**Comment by artemkhalygov** [comment]
I downgraded "@react-native-community/push-notification-ios" to 1.1.0 and now everything work as expected.

**Comment by Mura7** [comment]
> I downgraded "@react-native-community/push-notification-ios" to 1.1.0 and now everything work as expected.

its not working for me :(

**Comment by Mura7** [comment]
i am using firebase and its worked with upgrade to v6.4.1-alpha.0 [https://github.com/zo0r/react-native-push-notification/issues/1371#issuecomment-617588063](https://github.com/zo0r/react-native-push-notification/issues/1371#issuecomment-617588063)

**Comment by egor-a-trubnikov-panov** [comment]
I am experiencing the same issue. "@react-native-community/push-notification-ios": "^1.2.2"

**Comment by TommyLeong** [comment]
Tested with `"@react-native-community/push-notification-ios": "^1.4.1"` **still having issue**, local notification don't show.

```
const notification = {
        alertBody: 'Body',
        alertAction: "view",
        alertTitle: 'Title'
}

PushNotificationIOS.presentLocalNotification(notification)
```

**Comment by chrisbobbe** [comment]
Could this be caused by the use, [here](https://github.com/react-native-community/push-notification-ios/blob/v1.5.0/ios/RNCPushNotificationIOS.m#L383), of the deprecated method `presentLocalNotificationNow` ([Apple doc](https://developer.apple.com/documentation/uikit/uiapplication/1622931-presentlocalnotificationnow?language=objc)), without any other codepath (as far as I've seen—I could be missing it!) that's meant to be executed on iOS 10+?

**Comment by Ayse-Erduran** [comment]
I am experiencing the same issue. Were you able to figure out a solution?

**Comment by Naturalclar** [comment]
presentLocalNotification is now deprecated. please use addNotificationRequest introduced in v1.7.0
