### ISSUE TITLE
Correct Example for `soundName`

### ISSUE THREAD

**Issue by objectiveSee** [react-native-push-notification-ios/push-notification-ios#119]
# Question

It is unclear from the documentation what type of value to pass to `soundName` parameter when creating a push with `scheduleLocalNotification`. I have my file in `assets/bubble.wav` so I have tried various permutations such as `bubble,` `bubble.wav`,  `assets/bubble.wav`, and `assets/bubble`. Can anyone clarify? Does it need to be a file asset? Thank you!

```
const details = {
    fireDate: sendTime,
    alertTitle: title,
    alertBody: message,
    isSilent: false,
    userInfo: data,
    soundName: 'bubble',
    // applicationIconBadgeNumber: 69,
  };
  logger.info(`sending local notification: ${JSON.stringify(details, '  ', '  ')}`);
  PushNotificationIOS.scheduleLocalNotification(details);
```

**Comment by TommyLeong** [comment]
@objectiveSee Do oyu manage to find out what are the format type required here? Thank you.

**Comment by Naturalclar** [comment]
There's now a sample for using sound in the example repository :tada:
