### ISSUE TITLE
Notification with image 

### ISSUE THREAD

**Issue by girish54321** [react-native-push-notification-ios/push-notification-ios#161]
# Feature request

## Why it is needed

If we can have the option to show imageUrl on notification bar that will be great 

## Possible implementation

May be just pass imageUrl 

### Code sample
NA

**Comment by lukebars** [comment]
First of all, images would need to be fetched to local iphone storage to be shown on notification bar, so you would need to use rn-fetch-blob or something like that to store the image before scheduling notification.

**Comment by girish54321** [comment]
Oh but why not just pass image URL 🖼️

**Comment by santoshvarma4u** [comment]
Hey, I am also looking for similar behavior. Need to show an image on the notification.

**Comment by sahil290791** [comment]
Check this out for image support via Firebase: https://rnfirebase.io/messaging/ios-notification-images

**Comment by girish54321** [comment]
@sahil290791 Yes looks nice

**Comment by andrew-stupchuk** [comment]
> Check this out for image support via Firebase: https://rnfirebase.io/messaging/ios-notification-images

but this solution doesn't work for local notification. How did you solve this problem?
