### ISSUE TITLE
Displaying multiple when a notification arrives

### ISSUE THREAD

**Issue by mertbuldur** [react-native-push-notification-ios/push-notification-ios#167]
Hello , Displaying multiple when a notification arrives on IOS. My code is 
`PushNotification.configure({
  // (optional) Called when Token is generated (iOS and Android)

  onRegister: function (token) {
    //console.log("TOKEN:", token);
  },

  // (required) Called when a remote or local notification is opened or received
  onNotification: function (notification) {

    // process the notification

    // required on iOS only (see fetchCompletionHandler docs: https://github.com/react-native-community/react-native-push-notification-ios)
    if (!notification.foreground) {
     //notification.finish(PushNotificationIOS.FetchResult.NoData);
    }
    notification.finish(PushNotificationIOS.FetchResult.NoData);
  },

  // ANDROID ONLY: GCM or FCM Sender ID (product_number) (optional - not required for local notifications, but is need to receive remote push notifications)
  senderID: "503601710565",

  // IOS ONLY (optional): default: all - Permissions to register.
  permissions: {
    alert: true,
    badge: true,
    sound: true
  },
  // Should the initial notification be popped automatically
  // default: true
  popInitialNotification: true,

  /**
   * (optional) default: true
   * - Specified if permissions (ios) and token (android and ios) will requested or not,
   * - if not, you must call PushNotificationsHandler.requestPermissions() later
   */
  requestPermissions: true
});
`

ComponentDidMount:
` messaging().onMessage(notification => {
  
      console.log('2');
      PushNotification.localNotification({
        title:notification.notification.title,
        message:notification.notification.body, // (required),
      });
      console.log('Notification received!', notification);
    });`

**Comment by Naturalclar** [comment]
Fixed in v1.7.0
Notification with specific id should only display one at a time.

**Comment by akiladevinda** [comment]
@Naturalclar  I also facing this issue and I'm using version 1.5.0

Once I build and run the app from the codebase it will not be duplicated

But once I publish to Test flight it will duplicate same message twice

**Comment by vinay-sayone** [comment]
I'm getting 3 notifications when I sent a sample notification from firebase console. Anybody fixed this issue ?
