### ISSUE TITLE
Notification actions stopped working after upgrade from 1.0.3 to 1.4.0

### ISSUE THREAD

**Issue by varungupta85** [react-native-push-notification-ios/push-notification-ios#168]
# Feature request

Notification actions are an important part of iOS notifications which are missing from this package. I have been using https://github.com/holmesal/react-native-ios-notification-actions to handle notification actions in my app and they have been working well. But now after upgrade to `1.4.0`, the actions have stopped working probably because of the move the newer `UNUserNotificationCenter`. I have no experience with iOS development due to which I am not able to make required changes. The `react-native-ios-notification-actions` is no longer maintained.

I request that the notification actions be supported by this package directly as it is an integral part of iOS notifications and it would avoid many such incompatibility problems in the future.

## Why it is needed

iOS notification actions are an integral part of the notifications and should be supported by this package.

## Possible implementation

It would require adding the notification categories, notification actions and passing the events to the JS side when an action is taken as mentioned here https://developer.apple.com/documentation/usernotifications/handling_notifications_and_notification-related_actions

**Comment by Naturalclar** [comment]
@varungupta85 Notification Actions are now supported in v1.7.0 :tada:
