### ISSUE TITLE
Difference between React Native Core's implementation?

### ISSUE THREAD

**Issue by Li357** [react-native-push-notification-ios/push-notification-ios#18]
# Question

I understand this package is created in an effort to decouple React Native's core library from specific components. Is this supposed to be a mirror of React Native's PushNotificationIOS implementation or will all new commits to React Native's PushNotificationIOS be migrated here once it is deprecated?

If that's the case, should I be using this package or that from the core? I'm trying to write some TS types for this package so that I can use it in my project, but there is also a large discrepancy between `@types/react-native` and its actual implementation here and in the core package.

**Comment by Naturalclar** [comment]
The PushNotificationIOS implementation in react-native core is indeed deprecated and should not be used.
