### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by JamesPerlman** [react-native-push-notification-ios/push-notification-ios#189]
# Bug report

In the instructions for integrating UNUserNotificationCenter:

```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{
  completionHandler(UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionBadge);
}
```

This works however it is only correct because luckily the first 3 options in the `UNAuthorizationOptions` enum are identical in value to the elements of `UNNotificationPresentationOptions`.  The `completionHandler` should be called like so:
```
completionHandler(UNNotificationPresentationOptionBadge | UNNotificationPresentationOptionSound | UNNotificationPresentationOptionAlert)
```

**Comment by Naturalclar** [comment]
@JamesPerlman thanks for raising the issue!
This issue is solved in #172
