### ISSUE TITLE
Local push notifications not updating (overwriting)

### ISSUE THREAD

**Issue by hrishiakhade** [react-native-push-notification-ios/push-notification-ios#190]
# Question

Hello,
I am trying to add a timer feature in my app using local notifications. If I select timer for 60 seconds I get notifications every one second, since i don't want different notifications every second, I am passing the same hardcoded ID so that the new notification will just overwrite the previous one smoothly . This works perfectly fine on android, but not on ios. 

Is there any way to overwrite local notifications in ios using this same library? 

```
localNoti = (id=121) => {                    // i tried with 121 as well as '121' , not working on ios
    PushNotification.localNotification({
      /* Android Only Properties */
      autoCancel: true, // (optional) default: true
      channelId: NOTIFICATION_CHANNEL_ID,
      ongoing: false, // (optional) set whether this is an "ongoing" notification
      largeIcon: "",
      /* iOS only properties */
      alertAction: 'view', // (optional) default: view
      smallIcon: "ic_launcher",
      /* iOS and Android properties */
      playSound: false,
      vibrate: false,
      ignoreInForeground: true,
      title: "Timer", // (optional)
      message: this.state.currentTime, // this variabel updates every second
      id: id,                            // tried with ''+id      , not working on ios
      userInfo: { id: id }            // tried with  { id: ''+id }   not working on ios
    });
  }
```

```
"react": "16.11.0",
"react-native": "0.62.2",
"react-native-push-notification": "^6.1.0",
"@react-native-community/push-notification-ios": "^1.5.0",
```
Android : 

![android](https://user-images.githubusercontent.com/20705523/94785765-bb556380-03ed-11eb-95b0-3f89dcc2e5b0.gif)

iOS : 

![ios](https://user-images.githubusercontent.com/20705523/94785785-c1e3db00-03ed-11eb-8858-a282061660d1.gif)

**Comment by scgough** [comment]
Hi @hrishiakhade - on iOS are you cancelling the notification then rescheduling or just trying to overwrite it? 
I'm pretty sure you have to cancel then re-schedule the notification (by ID) for it to work.

**Comment by hrishiakhade** [comment]
@scgough just trying to overwrite it, I tried with cancelling and then again sending local notification. 
FYI, I am trying to invoke local notification every 1 second to update it. Seems like ios does not allow this.

**Comment by Naturalclar** [comment]
@hrishiakhade hello! sorry for the trouble.
I'll be adding a new method in the next version that should be able to solve this problem :)

**Comment by Naturalclar** [comment]
@hrishiakhade This should be possible with v1.7.0, use addNotificationRequest method, and set notification to have the same Id.

**Comment by hrishiakhade** [comment]
Thanks !!  Just checked, it's working fine !! Thanks for such a great library !!

**Comment by hrishiakhade** [comment]
@Naturalclar hi ,  I have noticed one issue. I'm calling local notification on ios after every second if app is in background. Let's say if set timer to 60 second then same  notification is displayed with different body text . This is works perfectly on simulator. But when run on Physical device , local notification  stopped coming after 30 seconds . Do u think this is library issue or I'm doing something wrong ..
