### ISSUE TITLE
Local Notification not working on IPad Air 2 IOS 13.8

### ISSUE THREAD

**Issue by densi97** [react-native-push-notification-ios/push-notification-ios#192]
We implemented firebase push notifications in our React Native App and use this package to present local notifications. Everything works fine (Foreground + Background Notifications) on IPhone 7, 8, X and 11. But on a IPad Air 2 running with IOS 13.8 from one of our clients it does not trigger the local notification when the app is in the background. We can assure the settings for notifications are correct. Is someone facing the same problem and has any fix for that?

**Comment by Naturalclar** [comment]
background notification seems to work fine on iPad pro with iOS 14.1
Could you try updating the notification package?

**Comment by densi97** [comment]
After updating all dependencies it works, thanks!
