### ISSUE TITLE
cancelAllLocalNotifications has been deprecated from iOS 10

### ISSUE THREAD

**Issue by Dallas62** [react-native-push-notification-ios/push-notification-ios#201]
Hi,

This issue refer to: https://github.com/zo0r/react-native-push-notification/issues/1716

> The API of iOS "cancelAllLocalNotifications" has been deprecated from iOS 11, so it doesn't not work from iOS 11 or above.

Here the replacement method:
https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649509-removeallpendingnotificationrequ

This is also probably the case for:
https://developer.apple.com/documentation/uikit/uiapplication?language=objc

- `scheduleLocalNotification`:
  > Schedules a local notification for delivery at its encapsulated date and time.
  Deprecated
- `presentLocalNotificationNow`
  > Presents a local notification immediately.
  Deprecated
- `cancelLocalNotification`
  > Cancels the delivery of the specified scheduled local notification. 
  Deprecated
- `cancelAllLocalNotifications`
  > Cancels the delivery of all scheduled local notifications.
  Deprecated
- `scheduledLocalNotifications`
  > All currently scheduled local notifications.
  Deprecated

cc @Naturalclar

**Comment by Naturalclar** [comment]
@Dallas62 thanks for the information! 
I'll add removeAllPendingNotificationRequests method for next version and deprecate cancelAllLocalNotifications method.

**Comment by Naturalclar** [comment]
I'll also work on other deprecated methods as well

**Comment by Naturalclar** [comment]
@Dallas62 I've added new methods that uses UNNotification instead of UILocalNotification in v1.7.0 :tada:
I plan to remove the deprecated methods in the next major version of this repo.
There will be some modification needed in the https://github.com/zo0r/react-native-push-notification side, just fyi :)

**Comment by Dallas62** [comment]
Thanks for this changes!
I will check that ASAP 😉

**Comment by YaoHuiJi** [comment]
Hi, @Dallas62 @Naturalclar  thanks for your works. I have a question, when I build my app, I get warnings in file 'RNCPushNotificationIOS.h', is this ok?

> 'UILocalNotification' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationRequest

> 'UIUserNotificationSettings' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationSettings
