### ISSUE TITLE
cancelLocalNotifications deprecated?

### ISSUE THREAD

**Issue by joebernard** [react-native-push-notification-ios/push-notification-ios#217]
`cancelLocalNotifications` is [marked as deprecated](https://github.com/react-native-push-notification-ios/push-notification-ios/blob/master/index.d.ts#L392) with a note to use `removeAllPendingNotificationRequests` instead.

However, `removeAllPendingNotificationRequests` cancels ALL scheduled notifications. It does not allow targeting of specific notifications to cancel. Is there an alternative to `cancelLocalNotifications` that will accept `userInfo` similar to `cancelLocalNotifications`?

Note that the [docs](https://github.com/react-native-push-notification-ios/push-notification-ios#cancellocalnotifications) do not show `cancelLocalNotifications` deprecated, it is just in the [declaration](https://github.com/react-native-push-notification-ios/push-notification-ios/blob/master/index.d.ts#L392).

**Comment by Naturalclar** [comment]
@joebernard Thanks for raising the issue!
It seems that I've missed that part of the specification.
I'll be adding another method that will allow specifying which notification to cancel in the next few days. Sorry about that!

**Comment by Naturalclar** [comment]
@joebernard `removePendingNotificationRequests` has been implemented in v1.8.0 :tada:
should replace cancelLocalNotifications method
