### ISSUE TITLE
pod install failed

### ISSUE THREAD

**Issue by code-by** [react-native-push-notification-ios/push-notification-ios#224]
React: 16.8.6
 RN: 0.60.5
 macOS: 10.15.6
react-native-push-notification-ios/push-notification-ios: 1.7.1

Build target: iOS 9

```
npx: installed 1 in 3.122s
Scanning for pods...
1.9.3
> pod install
Detected React Native module pod for RNCPushNotificationIOS
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "RNCPushNotificationIOS":
  In Podfile:
    RNCPushNotificationIOS (from `../node_modules/@react-native-community/push-notification-ios`)

Specs satisfying the `RNCPushNotificationIOS (from `../node_modules/@react-native-community/push-notification-ios`)` dependency were found, but they required a higher minimum deployment target.

Aborting run
```

**Comment by Naveen562117** [comment]
[!] CocoaPods could not find compatible versions for pod "RNCPushNotificationIOS":
  In Podfile:
    RNCPushNotificationIOS (from `../node_modules/@react-native-community/push-notification-ios`)

Specs satisfying the `RNCPushNotificationIOS (from `../node_modules/@react-native-community/push-notification-ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by Naveen562117** [comment]
hi I am getting the same issue since yesterday not able to install or run the code @code-by did you find any solution so far??

**Comment by gilsonviana-oowlish** [comment]
Same issue here.

**Comment by gilsonviana-oowlish** [comment]
Ok, I got it working here.

On the `Podfile`, do the following changes:

-`platform :ios, '9.0'`
+`platform :ios, '10.0'`

**Comment by Naveen562117** [comment]
@gilsonviana-oowlish thanks  but the error changed to  Invariant Violation: native module cannot be null
error,

**Comment by Nehal-29** [comment]
Can't increase the iOS target from 9 to 10. Any other solution?

**Comment by Naveen562117** [comment]
@Nehal-29 this is issue was resolved when I made it 9=> 10 but , and created one more new issue 
which 

Invariant Violation: Native module cannot be null.

invariant
    browser.js:38:14
constructor
    NativeEventEmitter.js:37:15
<global>
    index.js:17:46
loadModuleImplementation
    require.js:321:11
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:171700:51
loadModuleImplementation
    require.js:321:11
<global>
    index.tsx:10
loadModuleImplementation
    require.js:321:11
<global>
    App.js:2
loadModuleImplementation
    require.js:321:11
<global>
    index.js:6
loadModuleImplementation
    require.js:321:11
guardedLoadModule
    require.js:201:44
global code
    index.bundle?platform=ios&dev=true&minify=false:252997:3
     

and this error is not giving a clue about which. package is this error belongs to..

**Comment by Nehal-29** [comment]
This means one of your module is not linked or pod is not installed for that module

**Comment by unicornRainbows** [comment]
Rebuild you project in Xcode @Naveen562117

**Comment by Naveen562117** [comment]
@unicornRainbows I have rebuild the project like at least 30-40 times

**Comment by Naveen562117** [comment]
is there any other suggestion to how to get over with this issue @unicornRainbows

**Comment by Naveen562117** [comment]
hi in my case 

'react-native-play-install-referrer' was the package caused the issue Invariant Violation: Native module cannot be null.

 and not relevant to pod installation failed and ,,

changing iOS platform to 9.0 => 10.0 fixed this issue

**Comment by Naturalclar** [comment]
The push notification module are only supported for iOS10 and above.
Please update the ios version on the pod file

https://github.com/react-native-push-notification-ios/push-notification-ios/issues/224#issuecomment-722358678

**Comment by HammzaHM** [comment]
> Ok, I got it working here.
> 
> On the `Podfile`, do the following changes:
> 
> -`platform :ios, '9.0'`
> +`platform :ios, '10.0'`

This worked for me Thanks

**Comment by JeffPatricio** [comment]
> Ok, I got it working here.
> 
> On the `Podfile`, do the following changes:
> 
> -`platform :ios, '9.0'`
> +`platform :ios, '10.0'`

This worked for me Thanks

**Comment by Rushabhgedam** [comment]
Not worked for me, Still facing the same error

**Comment by acarkaan** [comment]
> #Ok, I got it working here.
> 
> On the Podfile, do the following changes:
> 
> -platform :ios, '9.0'
> +platform :ios, '10.0'

works Well Thanks...

**Comment by samuelprogramer** [comment]
Happened when I added `@react-native-async-storage/async-storage` library. I thought the cause could be her, but after removing it the problem continued. So I decided to see if it was something else, I deleted the IOS folder of my project and ran `expo eject` when I ran `pod install` it worked perfectly
