### ISSUE TITLE
Will `removePendingNotificationRequests` be supported in the next major release?

### ISSUE THREAD

**Issue by devinjameson** [react-native-push-notification-ios/push-notification-ios#239]
See [Apple](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649517-removependingnotificationrequest) for more info on the method. It will allow for particular pending notifications to be removed instead of all pending notifications.

**Comment by Naturalclar** [comment]
`removePendingNotificationRequests` has been implemented in v1.8.0 :tada:
