### ISSUE TITLE
Is support for react-native version 0.59 being discontinued?

### ISSUE THREAD

**Issue by hadimoha** [react-native-push-notification-ios/push-notification-ios#248]
Was having the issue of where the app was crashing on ios and tried this solution https://github.com/react-native-push-notification-ios/push-notification-ios/issues/163#issuecomment-733879096 but seems like from v 1.60 doesn't work on 0.59

**Comment by Naturalclar** [comment]
I'm expecting this module to work on version 0.59, could you tell me the specific error you're facing on 0.59?

**Comment by hadimoha** [comment]
from v1.60 the podspec requires **React-Core** which for me doesn't work with 0.59.

**Comment by Naturalclar** [comment]
@hadimoha thanks for the info! `React-Core` is indeed not supported in React Native < 0.59
The change from `React` to `React-Core` is required for Xcode v12+, so it will be difficult to support both React Native < 0.59 and Xcode > v12

**Comment by hadimoha** [comment]
exactly, will close this then. would be great if this indicated on the home page.
