### ISSUE TITLE
No IOS9 support?

### ISSUE THREAD

**Issue by ChrisEelmaa** [react-native-push-notification-ios/push-notification-ios#258]
After switching over from the old push-notification-ios package (importing directly from `react-native` package), it looks like ios9 <= devices are no longer supported due to using UserNotifications ios library (only available in IOS10>=).

Is this deliberate and this package only supports ios10+?

The crash error:

```
dyld: Library not loaded: /System/Library/Frameworks/UserNotifications.framework/UserNotifications
  Referenced from: /var/containers/Bundle/Application/...../MYApp/MYApp
  Reason: image not found
  ```

**Comment by chrisbobbe** [comment]
Right: https://github.com/react-native-push-notification-ios/push-notification-ios/issues/179.

**Comment by ChrisEelmaa** [comment]
cool! would be good to mention that in big text at readme.md, otherwise it is quite a little shocker as you deploy it to production and it takes whole app down for ios9+ users, some devices still have ios9 and can't be upgraded any further (for example ipad2). 

That said, we're happy to drop ios9 support in our app as the users who use it is very small percentage
