### ISSUE TITLE
Foreground notification for iOS 14

### ISSUE THREAD

**Issue by iagormoraes** [react-native-push-notification-ios/push-notification-ios#276]
The option Alert was deprecated in exchange of `UNNotificationPresentationOptionAlert` and `UNNotificationPresentationOptionList`, this means that iOS 14 or higher will not receive foreground push notifications with current version of this package.

Even calling `completionHandler(UNNotificationPresentationOptionBanner);` in AppDelegate it doesn't prompt the dialog in foreground.

**Comment by iagormoraes** [comment]
It seems was a bad setup to the AppDelegate file, it works with the documentation example:

```completionHandler(UNNotificationPresentationOptionSound | UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionBadge);```

**Comment by LightningNemesis** [comment]
I am still unable to receive notifications in the foreground, and the documentation example I have used is
 
`-(void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{
  completionHandler(UNNotificationPresentationOptionSound | UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionBadge);
}`

Could you help me out with this?

**Comment by thijs-qv** [comment]
[This](https://github.com/react-native-push-notification-ios/push-notification-ios/issues/256#issuecomment-863909897) works for me.
