### ISSUE TITLE
iOS13 push notifications failing

### ISSUE THREAD

**Issue by HanliTheron** [react-native-push-notification-ios/push-notification-ios#40]
# Feature

React native info output:

```bash
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 129.54 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.9 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by phpSing** [comment]
Also having issue to receive notification on iOS 13.1.2, any solutions?

**Comment by kilimchoi** [comment]
any solutions?

**Comment by HanliTheron** [comment]
Hi, this is caused by changes made by Apple, see: https://onesignal.com/blog/ios-13-introduces-4-breaking-changes-to-notifications/ 

I don't know if or when this package will update, you can try submitting a PR with the changes proposed in the article to maybe speed things up. I decided to make use of firebase local notifications instead.

**Comment by mike-roberts** [comment]
It looks like the implementation is correct in this plugin, according to the link @HanliTheron posted. https://github.com/react-native-community/react-native-push-notification-ios/blob/684c4bb516883dcaf28a75ca49d4ff6a7f27239e/ios/RNCPushNotificationIOS.m#L185-L196

Perhaps your issues are with the payload you're sending?  These two paragraphs highlight the important changes you need to make in your push payloads. https://onesignal.com/blog/ios-13-introduces-4-breaking-changes-to-notifications/#a-new-attribute-is-required-on-all-apns-apple-push-notification-service-api-headers- and https://onesignal.com/blog/ios-13-introduces-4-breaking-changes-to-notifications/#apns-priority-must-be-set-to-5-for-background-notifications

**Comment by Naturalclar** [comment]
Closing this issue for triaging purpose.
If you're still facing the issue, feel free to open another issue with repro code or repo
