### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by Naturalclar** [react-native-push-notification-ios/push-notification-ios#48]
# Question

It seems like this repository has not been touched in a while.
Is this repo in need for maintainers?
This repo was mentioned in https://github.com/react-native-community/discussions-and-proposals/issues/176#issuecomment-562354454 as one of the repos having trouble being maintained.

If it's something I can help, I'd like to stand up to be a maintainer help out the react-native-community.

Any thoughts?

**Comment by Gustash** [comment]
I'd like to apply as a maintainer as well. This package is using some deprecated APIs since iOS 10 and it's used by too many people. I think it should be actively maintained to avoid future issues for thousands of people.

**Comment by chrisbobbe** [comment]
> This package is using some deprecated APIs since iOS 10

It looks like https://github.com/react-native-community/push-notification-ios/pull/66 addressed some of this! Not sure if there are other cases, though. 🙂
