### ISSUE TITLE
This package doesn't work with RN 61.4

### ISSUE THREAD

**Issue by EsraaMahmoudMohamed** [react-native-push-notification-ios/push-notification-ios#50]
i followed documentation steps but push notification didn't work and allow notification popup didn't appear
https://github.com/react-native-community/react-native-push-notification-ios#getting-started

**Comment by lenichols** [comment]
Having the same issue... doesn't seem to work in 0.61.5 either.

**Comment by lenichols** [comment]
@EsraaMahmoudMohamed did you find a solution?

**Comment by ruyjfs** [comment]
Hello, my first comments on GitHub issues in a open source projeto..

In Old Doc, I get this and work for me...

[https://facebook.github.io/react-native/docs/pushnotificationios](https://facebook.github.io/react-native/docs/pushnotificationios)

At the top of your AppDelegate.m:

    #import <UserNotifications/UserNotifications.h>

`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  ...
  // Define UNUserNotificationCenter
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;

  return YES;
}

//Called when a notification is delivered to a foreground app.
-(void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{
  completionHandler(UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionBadge);
}
`

**Comment by Benzer1406** [comment]
Have the same issue with 0.61.2

**Comment by Mavenic** [comment]
It doesn't work with firebase, the registered tokens are not valid FCM tokens

**Comment by sam1ri** [comment]
I QUIT REACT NATIVE ! Full errors, few functionalities!

**Comment by Naturalclar** [comment]
Closing this issue for triaging purpose.
If issue still persists, please provide a repository that reproduces the issue
