### ISSUE TITLE
How should I get the details of these options such as 'alertAction' and 'category'

### ISSUE THREAD

**Issue by XHFkindergarten** [react-native-push-notification-ios/push-notification-ios#78]
# Question

although I have read the doc of pushNotificationIOS, I'm stil confused of the enum of some options. such as  ```alertAction```,```category```,```soundName```. how should I know the possible values ? Or is there any docs explaining these things

**Comment by mkausas** [comment]
@XHFkindergarten did you figure this out?

**Comment by Naturalclar** [comment]
I've updated the version and added some information about the new methods, hopefully that helps.

`alertAction` is now deprecated since it won't show up on iOS10+ devices 
`category` takes in any string.
`sound` takes in file name of sound file that you add to your project.
