### ISSUE TITLE
Interacting Notification with action buttons

### ISSUE THREAD

**Issue by chetanCyquent** [react-native-push-notification-ios/push-notification-ios#98]
# Question
I need to implement a feature in app, when notification receives and user longpress on that notification brings list of buttons below notification.

Like when missed call has action button called 'Call Back'

Wanted to know how we can implement with this lib or any other lib which supports this feature.

Your help is highly appreciable.

Thanks In Advance.

**Comment by mathiasmoeller** [comment]
@chetanCyquent did you find a solution for this?

**Comment by chetanCyquent** [comment]
Hi @mathiasmoeller,

This module does not support for rich notification.
There is one paid lib called Notifee, which allows such features.

For android, I made actions for notification using react-native-firebase v5 as free version.
Steps mentioned in their documents.
But no solution for iOS for open source.

I hope this helps you..

Thanks

**Comment by mathiasmoeller** [comment]
Thanks for the info!

**Comment by Naturalclar** [comment]
@chetanCyquent @mathiasmoeller 
Notifications with interactions are now supported in v1.7.0 :tada:
